version: '3'

services:
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./volumes/certbot/conf:/etc/letsencrypt
      - ./volumes/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on: 
      - mongo
      - mongo-express
    volumes:
      - ./volumes/certbot/conf:/etc/letsencrypt:ro
      - ./volumes/certbot/www:/var/www/certbot:ro
      - ./nginx/html/root:/html/root
      - ./app/client/dist:/html/app:ro
      - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/app.conf:ro
      - ./nginx/conf.d/main.conf:/etc/nginx/conf.d/main.conf:ro
      - ./nginx/conf.d/mongo.conf:/etc/nginx/conf.d/mongo.conf:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - backend

  mongo:
    image: mongo:4
    container_name: ${MONGODB_CONTAINER}
    expose:
      - ${MONGODB_PORT}
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    command: [
      "mongod",
      "--port", "${MONGODB_PORT}",
      "--auth"
    ]
    volumes:
      - ./data:/data/db
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASS}"

  mongo-express:
    image: mongo-express
    # no build
    container_name: ${ME_CONTAINER}
    depends_on:
      - mongo
    networks:
      - backend
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: "${ME_CONFIG_BASICAUTH_USERNAME}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${ME_CONFIG_BASICAUTH_PASSWORD}"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGODB_USER}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGODB_PASS}"
      ME_CONFIG_MONGODB_PORT: "${MONGODB_PORT}"
      ME_CONFIG_MONGODB_SERVER: "${MONGODB_HOST}"
      ME_CONFIG_MONGODB_PORT: "${MONGODB_PORT}"

  build-vue:
    image: node
    command: ["make"]
    working_dir: "/app"
    environment: 
      NODE_ENV: "production"
    volumes:
      - ./app/client:/app
    networks:
      - backend

  express-node:
    image: node:latest
    environment: 
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGODB_USER}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGODB_PASS}"
      ME_CONFIG_MONGODB_PORT: "${MONGODB_PORT}"
      ME_CONFIG_MONGODB_SERVER: "${MONGODB_HOST}"
      ME_CONFIG_MONGODB_PORT: "${MONGODB_PORT}"

networks: 
  backend: